# -*- coding: utf-8 -*-
"""Explained_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpkQTSKE_vAaP7PD67IyOgOTyIbnRMR4

**شرح الخلية:** استيراد المكتبات الأساسية اللي هنحتاجها في المشروع كله: numpy وpandas للتعامل مع البيانات، وmatplotlib وseaborn للرسم البياني.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**شرح الخلية:** ضبط إعدادات العرض في pandas عشان تظهر كل الأعمدة والصفوف والعرض الكامل للجدول من غير ما يتم اختصار أي حاجة عند الطباعة."""

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)

"""## reading data

**شرح الخلية:** قراءة ملف الـ CSV اللي فيه بيانات محطة الطاقة الشمسية وتحويله لـ DataFrame اسمه df.
"""

df = pd.read_csv("Synthetic-Solar-Farm-Stream-No-Repair.csv")

"""**شرح الخلية:** عرض شكل البيانات (عدد الصفوف وعدد الأعمدة) للتأكد من حجم الداتا اللي هنشتغل عليها."""

df.shape

"""**شرح الخلية:** عرض أول 5 صفوف من البيانات لأخذ لمحة سريعة عن شكل الأعمدة والقيم."""

df.head()

"""**شرح الخلية:** عرض آخر 5 صفوف من البيانات للتأكد إن الملف اتحمّل صح لحد آخره."""

df.tail()

"""**شرح الخلية:** عرض قائمة بكل أسماء الأعمدة الموجودة في الداتا."""

df.columns.tolist()

"""**شرح الخلية:** عرض معلومات عامة عن كل عمود: نوع البيانات (رقم/نص/تاريخ) وعدد القيم غير الفارغة، عشان نفهم شكل الداتا بسرعة."""

df.info()

"""Data Quality

**شرح الخلية:** حساب عدد القيم المفقودة (missing) في كل عمود.
"""

df.isnull().sum()

"""**شرح الخلية:** بناء جدول يوضح عدد ونسبة القيم المفقودة في كل عمود، ثم ترتيبه تنازليًا عشان نشوف الأعمدة الأكتر تأثرًا بالقيم الناقصة."""

missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": df.isnull().mean() * 100
})

missing.sort_values("Missing Count", ascending=False)

"""**شرح الخلية:** حساب عدد الصفوف المكررة بالكامل في الداتا."""

df.duplicated().sum()

"""**شرح الخلية:** رسم خريطة حرارية (heatmap) توضح أماكن القيم المفقودة بصريًا عبر كل الأعمدة والصفوف."""

plt.figure(figsize=(10,5))
plt.title("Missing Values Heatmap")
sns.heatmap(df.isnull(),yticklabels=False)
plt.xlabel("Columns")
plt.ylabel("Rows")
plt.show()

"""Target analysis

**شرح الخلية:** عرض عدد الصفوف لكل قيمة في عمود is_faulted (هل الجهاز فيه عطل ولا لأ).
"""

df["is_faulted"].value_counts()

"""**شرح الخلية:** عرض عدد الصفوف لكل قيمة في عمود fault_severity (شدة العطل)."""

df['fault_severity'].value_counts()

"""**شرح الخلية:** حساب نسبة كل قيمة في عمود is_faulted كنسبة مئوية من إجمالي البيانات."""

df["is_faulted"].value_counts(normalize=True) * 100

"""**شرح الخلية:** رسم بياني (countplot) يوضح توزيع الحالات الصحية مقابل حالات العطل (is_faulted) في الداتا."""

plt.figure(figsize=(7, 5))
plt.title("Target Distribution")
sns.countplot(data=df,x="is_faulted")
plt.xlabel("Fault Status")
plt.ylabel("Number of Observations")

plt.show()

"""## Device profile

**شرح الخلية:** حساب متوسط نسبة العطل (is_faulted) لكل جهاز (device) على حدة.
"""

device_fault_ratio = df.groupby("device")["is_faulted"].mean() * 100
device_fault_ratio

"""**شرح الخلية:** رسم بياني يوضح نسبة العطل لكل جهاز، عشان نشوف هل فيه أجهزة بتتعطل أكتر من غيرها."""

plt.figure(figsize=(10, 5))
plt.title("Fault Ratio per Device")
sns.barplot(x=device_fault_ratio.index, y=device_fault_ratio.values)
plt.xlabel("Device")
plt.ylabel("Fault Ratio (%)")
plt.show()

"""**شرح الخلية:** بناء جدول تقاطعي (crosstab) يوضح عدد كل نوع عطل (fault_labels) لكل جهاز."""

device_fault_types = pd.crosstab(df["device"], df["fault_labels"])
device_fault_types

"""**شرح الخلية:** رسم بياني عمودي متراكم (stacked bar) يوضح توزيع أنواع الأعطال المختلفة على كل جهاز."""

device_fault_types.plot(
    kind="bar",
    stacked=True,
    figsize=(12, 6)
)
plt.title("Fault Type Distribution per Device")
plt.xlabel("Device")
plt.ylabel("Count")
plt.legend(title="fault_labels", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.show()

"""**شرح الخلية:** حساب متوسط الطاقة المنتجة (active_power) لكل جهاز."""

device_power = df.groupby("device")["active_power"].mean()
device_power

"""**شرح الخلية:** رسم بياني يوضح متوسط الطاقة المنتجة لكل جهاز."""

plt.figure(figsize=(10, 5))
plt.title("Average Active Power per Device")
sns.barplot(x=device_power.index, y=device_power.values)
plt.xlabel("Device")
plt.ylabel("Average Active Power")
plt.show()

"""**شرح الخلية:** حساب متوسط نسبة الأداء (performance_ratio) لكل جهاز."""

device_pr = df.groupby("device")["performance_ratio"].mean()
device_pr

"""**شرح الخلية:** رسم بياني يوضح متوسط نسبة الأداء لكل جهاز."""

plt.figure(figsize=(10, 5))
plt.title("Average Performance Ratio per Device")
sns.barplot(x=device_pr.index, y=device_pr.values)
plt.xlabel("Device")
plt.ylabel("Average Performance Ratio")
plt.show()

"""Numerical Features Analysis

**شرح الخلية:** عرض أسماء الأعمدة الرقمية فقط في الداتا (باستثناء الأعمدة النصية والتاريخية).
"""

df.select_dtypes(include=np.number).columns

"""**شرح الخلية:** استخراج قائمة الأعمدة الرقمية مع استبعاد عمود الـ target (is_faulted) عشان نستخدمها في تحليل الفيتشرز."""

numeric_features = df.select_dtypes(
    include=np.number
).columns.drop("is_faulted")

numeric_features

"""**شرح الخلية:** عرض إحصائيات وصفية (المتوسط، الانحراف المعياري، أقل وأعلى قيمة...) لكل الأعمدة الرقمية."""

df[numeric_features].describe()

"""**شرح الخلية:** رسم Histogram لكل الأعمدة الرقمية عشان نشوف شكل توزيع كل فيتشر."""

df[numeric_features].hist(
    bins=30,
    figsize=(15, 10)
)

plt.tight_layout()
plt.show()

"""**شرح الخلية:** حساب درجة الالتواء (skewness) لكل الأعمدة الرقمية وترتيبها تنازليًا، عشان نعرف الأعمدة اللي توزيعها مش متماثل."""

skewness = df[numeric_features].skew().sort_values(ascending=False)

print(skewness)

"""See the Outliers

**شرح الخلية:** استخراج الأعمدة المستمرة (continuous) فقط، يعني اللي عندها أكتر من قيمتين مختلفتين (يعني مش أعمدة 0/1 ثنائية).
"""

continuous_features = [
    col for col in numeric_features
    if df[col].nunique() > 2
]

continuous_features

"""**شرح الخلية:** رسم Boxplot لكل الأعمدة المستمرة عشان نكشف بصريًا وجود قيم شاذة (outliers)."""

df[continuous_features].plot(
    kind="box",
    subplots=True,
    layout=(4, 4),
    figsize=(18, 14)
)

plt.tight_layout()
plt.show()

"""Explore Outliers

**شرح الخلية:** تعريف دالة check_outliers اللي بترسم Boxplot لعمود معين وتحسب الحدود العليا والسفلى باستخدام طريقة IQR، وتطبع عدد القيم الشاذة، وترجع النتائج في dict.
"""

def check_outliers(data, col, symmetric=True):
    """Boxplot + IQR-based outlier summary for one numeric column.

    symmetric=True checks both tails (lower and upper bound).
    symmetric=False checks the upper tail only (for columns where only
    unusually HIGH values are meaningful outliers, e.g. irradiance).

    Returns the bounds and outlier count so results can be inspected later,
    instead of just printing them.
    """
    plt.figure(figsize=(14, 5))
    sns.boxplot(x=data[col])
    plt.title(f"Boxplot of {col}", fontsize=18)
    plt.xlabel(col, fontsize=14)
    plt.tight_layout()
    plt.show()

    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    if symmetric:
        mask = (data[col] < lower_bound) | (data[col] > upper_bound)
    else:
        mask = data[col] > upper_bound
    outliers = data[col][mask]

    print(f"--- {col} ---")
    print("Q1:", Q1, "| Q3:", Q3, "| IQR:", IQR)
    print("Lower bound:", lower_bound, "| Upper bound:", upper_bound)
    print("Number of outliers:", len(outliers))
    if len(outliers) > 0:
        print("Min outlier:", outliers.min(), "| Max outlier:", outliers.max())
    print()

    return {"lower_bound": lower_bound, "upper_bound": upper_bound, "n_outliers": len(outliers)}

"""**شرح الخلية:** تطبيق دالة check_outliers على 4 أعمدة ظهر فيها outliers في الرسم السابق (irradiance, module_temp, inverter_temp, cloud_cover)، مع قرار بعدم حذف القيم دي لأنها قراءات منطقية فيزيائيًا مش أخطاء بيانات."""

outlier_summary = {}
outlier_summary["irradiance"] = check_outliers(df, "irradiance", symmetric=False)
outlier_summary["module_temp"] = check_outliers(df, "module_temp")
outlier_summary["inverter_temp"] = check_outliers(df, "inverter_temp")
outlier_summary["cloud_cover"] = check_outliers(df, "cloud_cover")

outlier_summary

"""Correlation Analysis

**شرح الخلية:** رسم خريطة حرارية (Correlation Heatmap) توضح العلاقة الخطية بين كل الأعمدة المستمرة وعمود is_faulted.
"""

plt.figure(figsize=(16, 12))
plt.title("Correlation Heatmap", fontsize=20)
sns.heatmap(
    df[continuous_features + ["is_faulted"]].corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.tight_layout()
plt.show()

"""## The relation between Features and 1st model"""

corr_with_target = (
    df[numeric_features]
    .corr()["active_power"]
    .sort_values(ascending=False)
)

corr_with_target

plt.figure(figsize=(18, 10))

plt.subplot(2, 3, 1)
plt.scatter(df["dc_current"], df["active_power"], alpha=0.3)
plt.title("DC Current vs Active Power")
plt.xlabel("DC Current")
plt.ylabel("Active Power")

plt.subplot(2, 3, 2)
plt.scatter(df["ac_current"], df["active_power"], alpha=0.3)
plt.title("AC Current vs Active Power")
plt.xlabel("AC Current")
plt.ylabel("Active Power")

plt.subplot(2, 3, 3)
plt.scatter(df["irradiance"], df["active_power"], alpha=0.3)
plt.title("Irradiance vs Active Power")
plt.xlabel("Irradiance")
plt.ylabel("Active Power")

plt.subplot(2, 3, 4)
plt.scatter(df["clear_sky_irradiance"], df["active_power"], alpha=0.3)
plt.title("Clear Sky Irradiance vs Active Power")
plt.xlabel("Clear Sky Irradiance")
plt.ylabel("Active Power")

plt.subplot(2, 3, 5)
plt.scatter(df["inverter_temp"], df["active_power"], alpha=0.3)
plt.title("Inverter Temperature vs Active Power")
plt.xlabel("Inverter Temperature")
plt.ylabel("Active Power")

plt.subplot(2, 3, 6)
plt.scatter(df["sun_elevation"], df["active_power"], alpha=0.3)
plt.title("Sun Elevation vs Active Power")
plt.xlabel("Sun Elevation")
plt.ylabel("Active Power")

plt.tight_layout()
plt.show()

"""## The relation between Features and 2nd model"""

corr_with_fault = (
    df[numeric_features.tolist() + ["is_faulted"]]
    .corr()["is_faulted"]
    .sort_values(ascending=False)
)

corr_with_fault

fault_features = [
    'day_length_hours',
    'ambient_temp',
    'module_temp',
    'inverter_temp',
    'sun_elevation',
    'clear_sky_irradiance',
    'ac_current',
    'dc_current'
]

fig, axes = plt.subplots(2, 4, figsize=(20, 10))

for ax, feature in zip(axes.flat, fault_features):

    sns.boxplot(
        data=df,
        x='is_faulted',
        y=feature,
        ax=ax
    )

    ax.set_title(feature)
    ax.set_xlabel("Is Faulted")
    ax.set_ylabel(feature)

plt.tight_layout()
plt.show()

"""## The relation between Features and third model

# fault soiling
"""

corr_soiling = (
    df.corr(numeric_only=True)["fault_soiling"]
    .sort_values(ascending=False)
)

corr_soiling

"""# fault_inverter_overheat"""

corr_overheat = (
    df.corr(numeric_only=True)["fault_inverter_overheat"]
    .sort_values(ascending=False)
)

corr_overheat

"""# fault_tracker_stuck"""

corr_tracker = (
    df.corr(numeric_only=True)["fault_tracker_stuck"]
    .sort_values(ascending=False)
)

corr_tracker

"""# fault_dc_string_outage"""

corr_string = (
    df.corr(numeric_only=True)["fault_dc_string_outage"]
    .sort_values(ascending=False)
)

corr_string

"""## The relation between Features and fourth model"""

# distribution
df["fault_severity"].value_counts().sort_index()

# percentage
df["fault_severity"].value_counts(normalize=True).sort_index().mul(100).round(2)

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="fault_severity",
    order=["none", "low", "medium", "high"]
)

plt.title("Fault Severity Distribution", fontsize=16)
plt.xlabel("Fault Severity")
plt.ylabel("Count")

plt.show()

"""## convert str to datetime and sorting

**شرح الخلية:** تحويل عمودي downtime_start_time وtime لنوع بيانات تاريخ/وقت (datetime)، ثم ترتيب الداتا حسب الوقت.
"""

df['downtime_start_time'] = pd.to_datetime(df['downtime_start_time'])
df['time'] = pd.to_datetime(df['time'])
df = df.sort_values('time')

"""**شرح الخلية:** استخراج فيتشرز زمنية جديدة من عمود time: الساعة، الشهر، يوم الأسبوع، وهل الوقت ده نهاري ولا لأ (is_daylight)، ثم تعيين عمود time كـ index للجدول."""

df['hour'] = df['time'].dt.hour
df['month'] = df['time'].dt.month
df['day_of_week'] = df['time'].dt.dayofweek
df['is_daylight'] = df['hour'].between(6, 18).astype(int)
df = df.set_index('time')

"""## Time gaps check

**شرح الخلية:** حساب الفرق الزمني بالدقايق بين كل قراءة والقراءة اللي قبلها لنفس الجهاز، عشان نكتشف أي فجوات (gaps) في تسلسل القراءات.
"""

time_series = df.index.to_series()
df["time_diff_min"] = time_series.groupby(df["device"]).diff().dt.total_seconds() / 60.0

"""**شرح الخلية:** تحديد الفجوة الزمنية المتوقعة (الأكتر تكرارًا) بين القراءات، وحساب عدد الفجوات الأكبر من المتوقع لكل جهاز."""

expected_gap_min = df["time_diff_min"].mode()[0]

gaps = df[df["time_diff_min"] > expected_gap_min]
gaps_per_device = gaps.groupby("device").size()

print("Expected gap between readings (minutes):", expected_gap_min)
print("Total gaps found:", len(gaps))
gaps_per_device

"""**شرح الخلية:** حذف عمود time_diff_min المؤقت بعد ما خلصنا استخدامه في فحص الفجوات الزمنية."""

df = df.drop(columns=["time_diff_min"])

"""## calculate downtime in min

**شرح الخلية:** حساب مدة التوقف (downtime_duration_min) بالدقايق من وقت بداية التوقف downtime_start_time لحد وقت القراءة الحالية، مع تعويض القيم الفارغة بصفر، ثم حذف عمود downtime_start_time الأصلي بعد استخراج المعلومة منه.
"""

df['downtime_duration_min'] = (df.index - df['downtime_start_time']).dt.total_seconds() / 60.0
df['downtime_duration_min'] = df['downtime_duration_min'].fillna(0).clip(lower=0)

df = df.drop(columns=['downtime_start_time'])

"""**شرح الخلية:** عرض أول صفوف من الداتا بعد إضافة الأعمدة الزمنية الجديدة للتأكد إن كل حاجة صح."""

df.head()

"""## one hot encoding

**شرح الخلية:** عرض عدد الصفوف لكل نوع عطل في عمود fault_labels.
"""

df['fault_labels'].value_counts()

"""**شرح الخلية:** عرض عدد الصفوف لكل قيمة في عمود fault_severity بعد الخطوات السابقة."""

df['fault_severity'].value_counts()

"""**شرح الخلية:** حساب dc_power وac_power من ضرب الجهد في التيار، وحساب كفاءة الإنفرتر (inverter_efficiency) كنسبة ac_power إلى dc_power مع تحديدها بين 0 و1، وأخيرًا تحويل fault_severity من نص إلى أرقام ترتيبية (none=0, low=1, medium=2, high=3)."""

df['dc_power'] = (df['dc_voltage'] * df['dc_current'])

df['ac_power'] = (df['ac_voltage'] * df['ac_current'])

df['inverter_efficiency'] = np.where(df['dc_power'] > 0, df['ac_power'] / df['dc_power'], 0.0)

df['inverter_efficiency'] = df['inverter_efficiency'].clip(lower=0.0, upper=1.0)

df['fault_severity'] = df['fault_severity'].map({'none':0,'low':1,'medium':2,'high':3})

"""## Check imbalance

### Is_faulted

**شرح الخلية:** طباعة عدد ونسبة كل قيمة في is_faulted، ورسم بياني يوضح التوزيع.
"""

print(df["is_faulted"].value_counts())
print()
print(df["is_faulted"].value_counts(normalize=True) * 100)

plt.figure(figsize=(7, 5))
plt.title("Distribution of is_faulted")
sns.countplot(data=df, x="is_faulted")
plt.xlabel("is_faulted")
plt.ylabel("Count")
plt.show()

"""### fault_labels

**شرح الخلية:** طباعة عدد ونسبة كل نوع عطل في fault_labels، ورسم بياني عمودي يوضح توزيع أنواع الأعطال المختلفة.
"""

print(df["fault_labels"].value_counts())
print()
print(df["fault_labels"].value_counts(normalize=True) * 100)

plt.figure(figsize=(10, 5))
plt.title("Distribution of fault_labels")
sns.countplot(data=df, x="fault_labels", order=df["fault_labels"].value_counts().index)
plt.xlabel("fault_labels")
plt.ylabel("Count")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""### fault_severity

**شرح الخلية:** طباعة عدد ونسبة كل مستوى شدة عطل في fault_severity، ورسم بياني يوضح التوزيع.
"""

print(df["fault_severity"].value_counts())
print()
print(df["fault_severity"].value_counts(normalize=True) * 100)

plt.figure(figsize=(7, 5))
plt.title("Distribution of fault_severity")
sns.countplot(data=df, x="fault_severity", order=df["fault_severity"].value_counts().index)
plt.xlabel("fault_severity")
plt.ylabel("Count")
plt.show()

"""## Train / Test Split — الاستراتيجية العامة (قبل ما نبدأ في أي موديل)

**شرح الخلية:** حساب نسبة العطل لكل شهر في السنة، ورسم بياني يوضح إن نسبة العطل مش متساوية على مدار السنة (فيه شهور بتتعطل فيها الأجهزة أكتر).
"""

monthly_fault_ratio = df.groupby(df.index.month)["is_faulted"].mean() * 100

plt.figure(figsize=(10, 5))
bars = plt.bar(monthly_fault_ratio.index, monthly_fault_ratio.values, color="#4C72B0")
plt.title("Fault Ratio per Month — NOT uniform across the year")
plt.xlabel("Month")
plt.ylabel("% is_faulted = 1")
plt.xticks(range(1, 13))
for b in bars:
    plt.text(b.get_x() + b.get_width()/2, b.get_height()+0.5, f"{b.get_height():.0f}%", ha="center", fontsize=9)
plt.tight_layout()
plt.show()

"""### الخطوة 2: الحل — Blocked Time Split لكل (device × week)

**شرح الخلية:** تعريف دالة time_block_split اللي بتقسم كل مجموعة (جهاز × أسبوع) زمنيًا: أول 80% من الصفوف يروحوا Train والـ 20% الباقيين يروحوا Test، عشان الـ train يسبق الـ test زمنيًا دايمًا. بعدين تطبيق التقسيم ده على كل جهاز وكل أسبوع على حدة وتجميع النتائج في train_df وtest_df.
"""

def time_block_split(group, train_frac=0.8):
    """Chronological 80/20 split within one group (device, week).
    First `train_frac` of the rows (already sorted by time) go to train,
    the last remaining rows go to test -> train always precedes test.
    """
    n = len(group)
    cut = int(np.floor(n * train_frac))
    return group.iloc[:cut], group.iloc[cut:]

df["week"] = df.index.isocalendar().week

train_parts, test_parts = [], []
for _, g in df.groupby(["device", "week"], sort=False):
    tr, te = time_block_split(g)
    train_parts.append(tr)
    test_parts.append(te)

train_df = pd.concat(train_parts).sort_index()
test_df = pd.concat(test_parts).sort_index()

df = df.drop(columns=["week"])
train_df = train_df.drop(columns=["week"])
test_df = test_df.drop(columns=["week"])

print("train_df:", train_df.shape)
print("test_df :", test_df.shape)
print(f"train is_faulted ratio: {train_df['is_faulted'].mean()*100:.2f}%")
print(f"test  is_faulted ratio: {test_df['is_faulted'].mean()*100:.2f}%")

"""### الخطوة 3: تأكيد بصري إن التقسيم فعلاً متوازن

**شرح الخلية:** رسم بياني للتأكد بصريًا إن نسبة is_faulted ونسبة fault_severity متقاربة جدًا بين مجموعة الـ train ومجموعة الـ test بعد التقسيم الأسبوعي.
"""

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
w = 0.35

ax = axes[0]
v_train = train_df["is_faulted"].mean() * 100
v_test = test_df["is_faulted"].mean() * 100
ax.bar(0 - w/2, v_train, w, label="Train", color="#4C72B0")
ax.bar(0 + w/2, v_test, w, label="Test", color="#DD8452")
ax.set_xticks([0]); ax.set_xticklabels(["is_faulted = 1"])
ax.set_ylabel("%"); ax.set_ylim(0, 30)
ax.set_title("is_faulted balance (weekly blocked split)")
ax.text(0 - w/2, v_train + 0.3, f"{v_train:.1f}%", ha="center")
ax.text(0 + w/2, v_test + 0.3, f"{v_test:.1f}%", ha="center")
ax.legend()

order = [0, 1, 2, 3]
labels = ["none", "low", "medium", "high"]
st = train_df["fault_severity"].value_counts(normalize=True).reindex(order) * 100
se = test_df["fault_severity"].value_counts(normalize=True).reindex(order) * 100
ax2 = axes[1]
xs = np.arange(4)
ax2.bar(xs - w/2, st.values, w, label="Train", color="#4C72B0")
ax2.bar(xs + w/2, se.values, w, label="Test", color="#DD8452")
ax2.set_xticks(xs); ax2.set_xticklabels(labels)
ax2.set_ylabel("% of rows")
ax2.set_title("fault_severity balance (weekly blocked split)")
ax2.legend()

plt.tight_layout()
plt.show()

"""النتيجة: نسبة `is_faulted` قريبة جدًا بين train و test (~20% مقابل ~21%)، وحتى الفئات النادرة `low` و`medium` في `fault_severity` بقت متمثلة في الاتنين تقريبًا بنفس النسبة. ده تحقق للشرطين اللي احنا عايزينهم من غير أي تعديل في الداتا نفسها.

> **ملحوظة مهمة:** `train_df` و `test_df` دول هيبقوا الأساس لكل الموديلات الأربعة. مش هنعيد التقسيم لكل موديل — هنستخدم نفس الصفوف، وبس هنختلف في الأعمدة (features) اللي هنسيبها حسب كل موديل، عشان نضمن كل الموديلات بتتقيم على نفس الأساس الزمني.

---
## موديل 1: توقع الطاقة المنتجة (`active_power`) — Regression

### الأعمدة اللي هتتشال (Data Leakage) بالنسبة للموديل ده تحديدًا

فيه مجموعتين من الأعمدة لازم تتشال:

**أ) أعمدة تسريب عامة (مرتبطة بالعطل — مالهاش لازمة هنا وبردو خطر تسريب لموديلات تانية):**
- `device` → لأنه بيسرب هوية الجهاز (كل جهاز مرتبط بعطل معين زي ما شفنا في الـ EDA)
- `is_faulted`, `fault_labels`, `fault_severity` → دول targets لموديلات تانية مش features
- `fault_soiling`, `fault_inverter_overheat`, `fault_tracker_stuck`, `fault_dc_string_outage` → أعلام (flags) مشتقة من نوع العطل نفسه
- `downtime_duration_min` → مشتق مباشرة من وجود عطل (زي ما وصفنا في تحليل الداتا)

**ب) أعمدة تسريب خاصة بموديل 1 (لأنها فعليًا نفس الـ target أو مشتقة منه رياضيًا):**
- `ac_power`, `dc_power` → الاتنين حسبناهم من الجهد والتيار، والـ correlation بتاعهم مع `active_power` أكتر من 0.99 (يعني هما نفس القيمة تقريبًا)
- `ac_voltage`, `ac_current`, `dc_voltage`, `dc_current` → هما نفسهم اللي بيتحسب منهم `active_power` أصلًا (لو سبناهم، الموديل هيعمل ضرب بسيط مش هيتعلم حاجة فيزيائية)
- `inverter_efficiency` → مبني على `ac_power` و `dc_power`
- `performance_ratio` → الـ correlation بتاعه مع `active_power` حوالي 0.80 (مشتق فعليًا من نسبة الإنتاج الفعلي للمتوقع)

باقي الأعمدة (`ambient_temp`, `module_temp`, `inverter_temp`, `cloud_cover`, `sun_elevation`, `sun_azimuth`, `day_length_hours`, `hour`, `month`, `day_of_week`, `is_daylight`, ...) دي فيتشرز فيزيائية/زمنية حقيقية تقدر تتوفر *قبل* ما نعرف الطاقة الناتجة — دي اللي هتفيد الموديل فعلًا يتعلم العلاقة الفيزيائية.

**ملحوظة:** عمود `irradiance` (شدة الإشعاع الشمسي) اتشال هو كمان من فيتشرز موديل 1 بقرار يدوي، عشان نجبر الموديل يعتمد على باقي المؤشرات الفيزيائية والزمنية (زي درجة الحرارة، الوقت، الغيوم...) من غير ما يعتمد اعتماد كامل على قيمة الإشعاع المباشرة.

**شرح الخلية:** تحديد الأعمدة اللي لازم تتشال من فيتشرز موديل 1 (توقع active_power) عشان تفادي تسريب البيانات (data leakage): أعمدة الهوية والـ targets الخاصة بالموديلات التانية، بالإضافة لأي عمود مشتق رياضيًا من active_power نفسه زي الجهد والتيار وperformance_ratio، وكمان عمود irradiance اتشال هو الآخر بقرار يدوي عشان الموديل ميعتمدش عليه كفيتشر مباشر.
"""

leakage_cols_general = [
    "device",
    "is_faulted", "fault_labels", "fault_severity",
    "fault_soiling", "fault_inverter_overheat", "fault_tracker_stuck", "fault_dc_string_outage",
    "downtime_duration_min",
]

model1_extra_leakage = [
    "active_power",
    "ac_power", "dc_power",
    "ac_voltage", "ac_current", "dc_voltage", "dc_current",
    "inverter_efficiency",
    "performance_ratio",
    "irradiance",
]

model1_drop_cols = leakage_cols_general + model1_extra_leakage
model1_features = [c for c in df.columns if c not in model1_drop_cols]

print("عدد الفيتشرز اللي هتستخدم في موديل 1:", len(model1_features))
model1_features

"""**شرح الخلية:** بناء بيانات التدريب والاختبار الخاصة بموديل 1: X_train_m1/X_test_m1 (الفيتشرز) وy_train_m1/y_test_m1 (الـ target وهو active_power)، مع طباعة أشكال (shapes) كل مجموعة."""

X_train_m1 = train_df[model1_features]
y_train_m1 = train_df["active_power"]

X_test_m1 = test_df[model1_features]
y_test_m1 = test_df["active_power"]

print("X_train_m1:", X_train_m1.shape)
print("X_test_m1 :", X_test_m1.shape)
print("y_train_m1:", y_train_m1.shape)
print("y_test_m1 :", y_test_m1.shape)

X_train_m1.head()

"""**شرح الخلية:** فحص تأكيدي (sanity check) لحساب الارتباط (correlation) بين كل فيتشر متبقي وعمود active_power، ورسمه بيانيًا، عشان نتأكد مفيش عمود لسه فيه تسريب بيانات مخفي (ارتباط قريب من 1)."""

corr_with_target = X_train_m1.select_dtypes(include=np.number).corrwith(y_train_m1).sort_values(ascending=False)

plt.figure(figsize=(8, 6))
corr_with_target.plot(kind="barh", color="#55A868")
plt.title("Correlation of remaining features with active_power (train set)")
plt.xlabel("Correlation")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

corr_with_target

"""---## موديل 2: هل الجهاز فيه عطل؟ (`is_faulted`) — Binary Classification### الأعمدة اللي هتتشال (Data Leakage) بالنسبة للموديل دههنا الوضع مختلف عن موديل 1. في موديل 1 كنا بنتوقع `active_power` نفسه، فكان لازم نشيل أي عمود مشتق منه رياضيًا (`ac_power`, `dc_power`, `performance_ratio`, ...). لكن هنا الـ target هو `is_faulted` (فيه عطل ولا لأ)، وده سؤال مختلف تمامًا عن قيمة الطاقة المنتجة.الأعمدة اللي **لازم تتشال** هنا هي بس أعمدة الـ "identity / target leakage" العامة اللي عرفناها فوق ومحفوظة في المتغير `leakage_cols_general` (مش هنعيد تعريفه، هو لسه موجود من قسم موديل 1):- **`device`** → عشان مش عايزين الموديل يحفظ إن PV001 دايمًا بيبقى فيه عطل بنسبة 43.8%، عايزينه يتعلم من القراءات الفيزيائية نفسها.- **`fault_labels`, `fault_severity`** → دول targets لموديلات تانية (3، 4) مش features هنا.- **`fault_soiling`, `fault_inverter_overheat`, `fault_tracker_stuck`, `fault_dc_string_outage`** → أعلام بتقول "فيه عطل نوع كذا" — لو سبناها الموديل هيغش، لأنها بتساوي `is_faulted = 1` تلقائيًا (لو أي علم منهم = 1 يبقى أكيد فيه عطل).- **`downtime_duration_min`** → مشتق أصلًا من وجود عطل (زي ما شفنا في الـ EDA).### الفرق المهم عن موديل 1هنا `active_power`, `performance_ratio`, `inverter_efficiency`, `ac_power`, `dc_power`, وكل قراءات الجهد/التيار **مش تسريب** — دي بالظبط الأعراض (symptoms) اللي المفروض الموديل يتعلم منها إن فيه عطل. لو جهاز طالع `performance_ratio` واطي جدًا وقت الشمس، ده أصلًا الدليل الفيزيائي على وجود مشكلة. تسريب موديل 1 كان لأن الهدف كان "احسب نفس الرقم اللي هو أصلًا مكتوب في عمود تاني"، أما هنا الهدف "صنّف الحالة"، فالقراءات دي أدلة شرعية (legitimate evidence) مش غش.

**شرح الخلية:** تحديد فيتشرز موديل 2 (توقع is_faulted): هنا بس أعمدة تسريب الهوية والـ targets العامة هي اللي بتتشال، أما باقي القراءات الفيزيائية زي active_power وperformance_ratio فهي أدلة شرعية على وجود عطل مش تسريب.
"""

model2_drop_cols = leakage_cols_general
model2_features = [c for c in df.columns if c not in model2_drop_cols]

print("عدد الفيتشرز اللي هتستخدم في موديل 2:", len(model2_features))
model2_features

"""**شرح الخلية:** بناء بيانات التدريب والاختبار الخاصة بموديل 2: X_train_m2/X_test_m2 وy_train_m2/y_test_m2 (الـ target هو is_faulted)."""

X_train_m2 = train_df[model2_features]
y_train_m2 = train_df["is_faulted"]

X_test_m2 = test_df[model2_features]
y_test_m2 = test_df["is_faulted"]

print("X_train_m2:", X_train_m2.shape)
print("X_test_m2 :", X_test_m2.shape)
print("y_train_m2:", y_train_m2.shape)
print("y_test_m2 :", y_test_m2.shape)

X_train_m2.head()

"""### تأكيد بصري: هل الفيتشرز فعلاً بتفرّق بين الحالتين؟نسبة `is_faulted` بين train و test اتأكدنا منها بالفعل في خطوة التقسيم فوق (~20% مقابل ~21%). دلوقتي هنتأكد كمان إن فيتشر زي `performance_ratio` فعلاً بيدي إشارة حقيقية تفرّق بين الحالتين — لو الاتنين شبه بعض تمامًا كان معناه الفيتشر مش هيفيد الموديل.

**شرح الخلية:** رسم Boxplot يوضح الفرق في performance_ratio بين الحالات السليمة والمعطلة، للتأكد إن الفيتشر ده بيدي إشارة حقيقية تفرّق بين الحالتين.
"""

plt.figure(figsize=(8, 5))
sns.boxplot(data=train_df, x="is_faulted", y="performance_ratio")
plt.title("Performance Ratio by Fault Status (train set)")
plt.xlabel("is_faulted")
plt.ylabel("performance_ratio")
plt.show()

"""---## موديل 3: نوع العطل (`fault_labels`) — Multi-class Classification### الأعمدة اللي هتتشالنفس فكرة موديل 2 بالظبط — الفيتشرز الفيزيائية (`active_power`, `performance_ratio`, `inverter_efficiency`, ...) شرعية هنا كمان، لأنها هي اللي هتفرّق بين أنواع الأعطال المختلفة (مثلاً `inverter_efficiency` واطي = مؤشر قوي لـ `inverter_overheat`، أما `performance_ratio` واطي مع إن الـ `irradiance` طبيعي = مؤشر لـ `soiling`).اللي هيتشال بردو هو نفسه `leakage_cols_general`:- **`device` → الأهم هنا.** زي ما شفنا في الـ EDA، كل جهاز مرتبط بنوع عطل واحد شبه حصري (PV001 → soiling بس، PV002 → inverter_overheat بس، PV003 → tracker_stuck بس، PV004 → dc_string_outage بس، PV000 → healthy تمامًا). لو سبنا العمود ده، الموديل مش هيتعلم الفيزياء خالص، هيحفظ رقم الجهاز وبس — وده أخطر تسريب في المشروع كله بالنسبة لموديل تصنيف نوع العطل تحديدًا.- `is_faulted`, `fault_severity` → targets لموديلات تانية، مش features هنا.- الأعلام الأربعة (`fault_soiling`, `fault_inverter_overheat`, `fault_tracker_stuck`, `fault_dc_string_outage`) → دي فعليًا الإجابة نفسها مقسّمة على أعمدة (زي one-hot تقريبًا)، سيبها = غش صريح.- `downtime_duration_min` → مشتق من وجود العطل.يبقى الفيتشرز هتكون **نفسها بالظبط** اللي استخدمناها في موديل 2 — الفرق الوحيد هو الـ target.

**ملحوظة إضافية:** الفئة النادرة `dc_string_outage|downtime` (فئة مركّبة بتظهر لما عطلين يحصلوا مع بعض) اتشالت خالص من الـ target بتاع موديل 3 — مش هتتستخدم لا كـ feature ولا كـ target — لأنها فئة نادرة جدًا (عدد قليل من الصفوف) وممكن تلخبط الموديل أكتر ما تفيده.

**شرح الخلية:** تحديد فيتشرز موديل 3 (توقع نوع العطل fault_labels): نفس فكرة موديل 2 تمامًا، بس هنا الأهم هو حذف عمود device عشان كل جهاز مرتبط بنوع عطل واحد شبه حصري.
"""

model3_drop_cols = leakage_cols_general
model3_features = [c for c in df.columns if c not in model3_drop_cols]

print("عدد الفيتشرز اللي هتستخدم في موديل 3:", len(model3_features))
print("هل نفس فيتشرز موديل 2؟", model3_features == model2_features)

"""**شرح الخلية:** بناء بيانات التدريب والاختبار الخاصة بموديل 3: X_train_m3/X_test_m3 وy_train_m3/y_test_m3 (الـ target هو fault_labels). بعد كده بيتم استبعاد الفئة النادرة والمركّبة dc_string_outage|downtime بالكامل من الـ train والـ test، فمش هتظهر كـ target ولا هتستخدم في تدريب الموديل خالص."""

X_train_m3 = train_df[model3_features]
y_train_m3 = train_df["fault_labels"]

X_test_m3 = test_df[model3_features]
y_test_m3 = test_df["fault_labels"]

excluded_label_m3 = "dc_string_outage|downtime"
train_mask_m3 = y_train_m3 != excluded_label_m3
test_mask_m3 = y_test_m3 != excluded_label_m3

X_train_m3 = X_train_m3[train_mask_m3]
y_train_m3 = y_train_m3[train_mask_m3]
X_test_m3 = X_test_m3[test_mask_m3]
y_test_m3 = y_test_m3[test_mask_m3]

print("X_train_m3:", X_train_m3.shape)
print("X_test_m3 :", X_test_m3.shape)
print("y_train_m3:", y_train_m3.shape)
print("y_test_m3 :", y_test_m3.shape)

X_train_m3.head()

"""### تأكيد بصري: توزيع أنواع الأعطال (`fault_labels`) بين train و testده أهم تأكيد لموديل 3 تحديدًا — المفروض كل الأنواع (حتى النادرة زي بعض الحالات) تكون ممثّلة بنسب متقاربة في الاتنين، بفضل التقسيم الأسبوعي لكل جهاز اللي عملناه فوق.

**شرح الخلية:** مقارنة توزيع أنواع الأعطال (fault_labels) بين train وtest بعد استبعاد الفئة dc_string_outage|downtime، ورسمها بيانيًا للتأكد إن كل الأنواع الباقية ممثّلة بنسب متقاربة في الاتنين.
"""

train_counts_lbl = y_train_m3.value_counts(normalize=True) * 100
test_counts_lbl = y_test_m3.value_counts(normalize=True) * 100

compare_labels_df = pd.DataFrame({"Train %": train_counts_lbl, "Test %": test_counts_lbl}).fillna(0)
compare_labels_df = compare_labels_df.sort_values("Train %", ascending=False)

compare_labels_df.plot(kind="bar", figsize=(10, 5), color=["#4C72B0", "#DD8452"])
plt.title("Fault Labels Distribution — Train vs Test")
plt.xlabel("fault_labels")
plt.ylabel("% of rows")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

compare_labels_df

"""---## موديل 4: شدة العطل (`fault_severity`) — Ordinal / Multi-class Classification### الأعمدة اللي هتتشالنفس المنطق تمامًا زي موديل 2 و3 — الفيتشرز الفيزيائية مسموحة (هي فعليًا أدلة على شدة العطل: كل ما `performance_ratio` بينزل أكتر، كل ما العطل غالبًا أشد). واللي بيتشال هو `leakage_cols_general` نفسه (`device`, `is_faulted`, `fault_labels`, الأعلام الأربعة، `downtime_duration_min`).`fault_severity` نفسه اتحوّل بالفعل لأرقام ordinal (`none=0, low=1, medium=2, high=3`) في خطوة الـ Feature Engineering فوق، يبقى جاهز يتستخدم كـ target مباشرة من غير أي تعديل تاني.

**شرح الخلية:** تحديد فيتشرز موديل 4 (توقع شدة العطل fault_severity): نفس فيتشرز موديل 2 وموديل 3 بالظبط، والفرق الوحيد هو الـ target.
"""

model4_drop_cols = leakage_cols_general
model4_features = [c for c in df.columns if c not in model4_drop_cols]

print("عدد الفيتشرز اللي هتستخدم في موديل 4:", len(model4_features))
print("هل نفس فيتشرز موديل 2 و3؟", model4_features == model2_features == model3_features)

"""**شرح الخلية:** بناء بيانات التدريب والاختبار الخاصة بموديل 4: X_train_m4/X_test_m4 وy_train_m4/y_test_m4 (الـ target هو fault_severity)."""

X_train_m4 = train_df[model4_features]
y_train_m4 = train_df["fault_severity"]

X_test_m4 = test_df[model4_features]
y_test_m4 = test_df["fault_severity"]

print("X_train_m4:", X_train_m4.shape)
print("X_test_m4 :", X_test_m4.shape)
print("y_train_m4:", y_train_m4.shape)
print("y_test_m4 :", y_test_m4.shape)

X_train_m4.head()

"""### تأكيد بصري: توزيع شدة العطل (`fault_severity`) بين train و test

**شرح الخلية:** مقارنة توزيع مستويات شدة العطل (fault_severity) بين train وtest، ورسمها بيانيًا للتأكد من التوازن بين المجموعتين.
"""

sev_labels = {0: "none", 1: "low", 2: "medium", 3: "high"}

train_counts_sev = y_train_m4.value_counts(normalize=True).reindex([0, 1, 2, 3]) * 100
test_counts_sev = y_test_m4.value_counts(normalize=True).reindex([0, 1, 2, 3]) * 100

compare_sev_df = pd.DataFrame({"Train %": train_counts_sev, "Test %": test_counts_sev})
compare_sev_df.index = compare_sev_df.index.map(sev_labels)

compare_sev_df.plot(kind="bar", figsize=(8, 5), color=["#4C72B0", "#DD8452"])
plt.title("Fault Severity Distribution — Train vs Test")
plt.xlabel("fault_severity")
plt.ylabel("% of rows")
plt.tight_layout()
plt.show()

compare_sev_df

"""---## الخلاصة: كل حاجة جاهزة قبل الموديلينجدلوقتي عندنا 4 مجموعات بيانات جاهزة، كلها مبنية على نفس التقسيم الزمني المتوازن (`train_df` / `test_df`)، وكل مجموعة بس بتختلف في الـ target والأعمدة المسموح بيها حسب السؤال اللي بتجاوبه:| الموديل | الـ Target | نوع المشكلة | الفيتشرز | نقطة التوازن اللي اتأكدنا منها ||---|---|---|---|---|| 1 | `active_power` | Regression | أقل من الباقي (شلنا كل أعمدة الطاقة/الجهد/التيار كمان) | مش وارد هنا (مش تصنيف) || 2 | `is_faulted` | Binary Classification | `model2_features` | ~20% مقابل ~21% || 3 | `fault_labels` | Multi-class Classification | نفسها (`model3_features == model2_features`) | كل الأنواع (حتى النادرة) ممثّلة بنسب متقاربة || 4 | `fault_severity` | Ordinal Classification | نفسها (`model4_features == model2_features`) | نسب متقاربة، وطبيعي تشبه `is_faulted` لأنها مبنية عليه |**اللي لسه محتاجينه قبل ما ندخل نبني الموديلات فعليًا (الخطوة الجاية):**- Scaling للفيتشرز العددية — لو هنجرب Linear/Logistic كـ baseline. الـ tree-based models زي CatBoost/LightGBM مش محتاجاها أصلًا (زي ما اتكلمنا في تحليل الـ skewness فوق).- التأكد مفيش أعمدة categorical نصية متبقية محتاجة encoding قبل ما تدخل الموديل.- تحديد استراتيجية التعامل مع الـ imbalance في موديل 3 و4 تحديدًا (`class_weight` غالبًا هيكون كافي هنا لأن التقسيم نفسه متوازن، لسه ممكن نحتاجه لو الموديل بدأ يميل للـ class الأكبر) واختيار الـ metric المناسب (`f1_macro` / `recall` لكل class بدل `accuracy` العادي، خصوصًا مع `low` و`medium`).كل ده هيبقى نقطة البداية في الجزء الجاي: الموديلينج نفسه.

---
# الجزء التاني: الموديلينج الفعلي (Modeling)

كل حاجة قبل كده كانت تجهيز (EDA + تنضيف + تقسيم زمني متوازن + تحديد الفيتشرز الصح لكل موديل من غير أي data leakage). دلوقتي عندنا 4 مجموعات بيانات جاهزة (`X_train_m1..m4`, `y_train_m1..m4`, `X_test_m1..m4`, `y_test_m1..m4`) ومفيش أي حاجة هتتعدل في `train_df` / `test_df` نفسهم.

هنمشي **موديل موديل**. في كل موديل هنعمل نفس الخطوات بالظبط:

1. **نجرب CatBoost.**
2. **نجرب LightGBM.**
3. **نقيّم الاتنين** بنفس الـ metrics ونحطهم جنب بعض في جدول.
4. **نرسم** (predicted vs actual / confusion matrix / feature importance حسب نوع الموديل) عشان نفهم مش بس نقرأ أرقام.
5. **نفسر** النتيجة: مين كسب وليه، والفيتشرز اللي الموديل اعتمد عليها بتتفق مع الفيزياء اللي احنا عارفينها ولا لأ.

### ليه CatBoost و LightGBM بالتحديد؟ (زي ما انت مش عارف حاجة عن الموديلين دول)

الاتنين نوعهم **Gradient Boosted Trees** — يعني بيبنوا مجموعة كبيرة من الأشجار القرار (decision trees) الواحدة ورا التانية، كل شجرة جديدة بتحاول **تصلّح غلط** الأشجار اللي قبلها، مش تتعلم من الصفر. النتيجة النهائية = مجموع (أو تصويت) كل الأشجار دي مع بعض.

ليه هما مناسبين للداتا بتاعتنا تحديدًا؟

- إحنا شفنا في الـ EDA إن الفيتشرز عندها **skewness** (زي `irradiance` اللي فيه أصفار كتير بالليل) — الموديلات الشجرية دي **مش حساسة للـ skewness أو للـ scale خالص**، يعني معندناش داعي نعمل `StandardScaler` أو أي transformation قبل ما ندخلهم للموديل (عكس Linear/Logistic Regression اللي كانوا محتاجينها).
- بيتعاملوا كويس جدًا مع **العلاقات الغير خطية** (non-linear relationships) — زي العلاقة بين `irradiance` و`active_power` اللي مش خط مستقيم بالظبط (فيه تشبع، وفيه تأثير حرارة على الكفاءة...).
- بيدونا **Feature Importance** جاهزة، يعني نقدر نشوف بعد التدريب مباشرة الموديل اعتمد على إيه أكتر — وده هيفيدنا نتأكد إن الموديل بيتعلم فيزياء حقيقية مش بيحفظ.
- CatBoost مشهور إنه بيدي نتايج كويسة "من غير ما تتعب في الـ tuning" (defaults قوية)، وLightGBM مشهور إنه **سريع جدًا** حتى على داتا كبيرة زي بتاعتنا (525 ألف صف).

**شرح الخلية:** استيراد مكتبات بناء الموديلات (CatBoost وLightGBM) ومقاييس التقييم (MAE, RMSE, R2, Accuracy, F1, وغيرهم) اللي هنحتاجها في كل الموديلات الأربعة.
"""

from catboost import CatBoostRegressor, CatBoostClassifier
from lightgbm import LGBMRegressor, LGBMClassifier

from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix, roc_auc_score, roc_curve
)

"""---
## موديل 1: التدريب والتقييم — CatBoost vs LightGBM (Regression)

الـ target هنا رقم مستمر (`active_power`)، يعني احنا في عالم الـ **Regression**. معنى إننا "كسبنا" هنا = الرقم اللي الموديل توقعه قريب من الرقم الحقيقي، مش "صح/غلط" زي التصنيف.

### قبل ما نشغّل: هنقيّم بإيه؟ (اشرحلي زي ما انا مش فاهم حاجة)

هنستخدم 3 مقاييس، كل واحد بيحكي جزء مختلف من القصة:

- **MAE (Mean Absolute Error):** لو الموديل توقع 500 والحقيقي كان 520، يبقى الغلط هنا 20. الـ MAE هو **متوسط** كل الغلطات دي (كلها موجبة، مفيش سالب). ميزته إنه **سهل الفهم** لأنه بنفس وحدة الـ target نفسه (يعني لو `active_power` بالـ kW، الـ MAE هيبقى بالـ kW برضو). لو MAE = 15 معناه "في المتوسط، توقع الموديل بعيد عن الحقيقة بمقدار 15 وحدة".
- **RMSE (Root Mean Squared Error):** زي الـ MAE، بس **بيربّع الغلط الأول قبل المتوسط وبعدين بياخد الجذر**. النتيجة: أي غلطة **كبيرة جدًا** (outlier prediction) بتتعاقب أكتر بكتير من الغلطات الصغيرة. لو RMSE أكبر بكتير من MAE، ده معناه فيه شوية توقعات غلط جدًا (مش غلط بسيط منتشر على الكل).
- **R² (R-squared):** ده مش وحدة زي الاتنين اللي فوق، ده **نسبة من صفر لواحد** (ممكن يبقى سالب لو الموديل وحش جدًا). بيقولك: "الموديل قدر يفسّر كام % من التغيّر (variance) اللي حصل في `active_power`؟". R² = 0.95 معناه الموديل فسّر 95% من التغير في الطاقة المنتجة اعتمادًا على الفيتشرز (irradiance, temp, ...)، والـ 5% الباقيين ممكن يكونوا noise أو عوامل مش موجودة في الداتا.

**القاعدة البسيطة:** MAE و RMSE **كل ما قلّوا كان أحسن**، R² **كل ما قرب من 1 كان أحسن**.

**شرح الخلية:** تدريب موديل CatBoost Regressor على بيانات موديل 1 لتوقع active_power، ثم استخدامه لعمل تنبؤات على بيانات الاختبار.
"""

cat_reg_m1 = CatBoostRegressor(
    iterations=600,
    learning_rate=0.05,
    depth=8,
    loss_function="RMSE",
    random_state=42,
    verbose=False
)

cat_reg_m1.fit(X_train_m1, y_train_m1)

pred_cat_m1 = cat_reg_m1.predict(X_test_m1)

"""**شرح الخلية:** تدريب موديل LightGBM Regressor على نفس بيانات موديل 1، ثم عمل تنبؤات على بيانات الاختبار."""

lgbm_reg_m1 = LGBMRegressor(
    n_estimators=600,
    learning_rate=0.05,
    max_depth=8,
    random_state=42,
    verbose=-1
)

lgbm_reg_m1.fit(X_train_m1, y_train_m1)

pred_lgbm_m1 = lgbm_reg_m1.predict(X_test_m1)

"""**شرح الخلية:** تعريف دالة regression_report بتحسب مقاييس التقييم الثلاثة (MAE, RMSE, R2) لأي موديل وتطبعها بشكل واضح وترجعها في dict، ثم استخدامها لتقييم نتائج CatBoost وLightGBM لموديل 1 وتجميعهم في جدول واحد."""

def regression_report(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    print(f"--- {model_name} (Model 1: active_power) ---")
    print(f"MAE  : {mae:.3f}")
    print(f"RMSE : {rmse:.3f}")
    print(f"R2   : {r2:.4f}")
    print()

    return {"Model": model_name, "MAE": mae, "RMSE": rmse, "R2": r2}

results_m1 = []
results_m1.append(regression_report(y_test_m1, pred_cat_m1, "CatBoost"))
results_m1.append(regression_report(y_test_m1, pred_lgbm_m1, "LightGBM"))

results_m1_df = pd.DataFrame(results_m1)
results_m1_df

"""### تصور بصري 1: مقارنة الـ 3 metrics بين الموديلين جنب بعض

**شرح الخلية:** رسم بياني يقارن قيم MAE وRMSE وR2 بين موديلي CatBoost وLightGBM جنب بعض لموديل 1.
"""

fig, axes = plt.subplots(1, 3, figsize=(16, 4.5))
metrics_m1 = ["MAE", "RMSE", "R2"]
colors_m1 = ["#4C72B0", "#DD8452"]

for ax, metric in zip(axes, metrics_m1):
    bars = ax.bar(results_m1_df["Model"], results_m1_df[metric], color=colors_m1)
    ax.set_title(metric, fontsize=14)
    for b in bars:
        ax.text(b.get_x() + b.get_width()/2, b.get_height(), f"{b.get_height():.3f}",
                 ha="center", va="bottom", fontsize=10)

plt.suptitle("Model 1 (active_power) — CatBoost vs LightGBM", fontsize=15)
plt.tight_layout()
plt.show()

"""### تصور بصري 2: Predicted vs Actual

النقط دي كل واحدة بتمثل صف من صفوف الـ test. المحور الأفقي = الرقم الحقيقي، المحور الرأسي = رقم الموديل توقعه. **لو الموديل مثالي 100%**، كل النقط هتقع بالظبط على الخط الأحمر (y = x). كل ما النقط قربت من الخط، كل ما الموديل كان أدق.

**شرح الخلية:** رسم Scatter Plot يقارن القيم المتوقعة بالقيم الحقيقية لـ active_power لكل من CatBoost وLightGBM، مع خط مرجعي (y=x) يمثل التنبؤ المثالي.
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

preds_m1 = {"CatBoost": pred_cat_m1, "LightGBM": pred_lgbm_m1}
max_val = max(y_test_m1.max(), pred_cat_m1.max(), pred_lgbm_m1.max())

for ax, (name, pred) in zip(axes, preds_m1.items()):
    ax.scatter(y_test_m1, pred, alpha=0.08, s=6, color="#4C72B0")
    ax.plot([0, max_val], [0, max_val], color="red", linestyle="--", linewidth=1.5, label="Perfect prediction (y = x)")
    ax.set_xlabel("Actual active_power")
    ax.set_ylabel("Predicted active_power")
    ax.set_title(name)
    ax.legend()

plt.suptitle("Model 1 — Predicted vs Actual (test set)", fontsize=15)
plt.tight_layout()
plt.show()

"""### تصور بصري 3: توزيع الأخطاء (Residuals)

الـ **residual** = القيمة الحقيقية − قيمة الموديل المتوقعة. لو residual موجب يبقى الموديل **قلّل التقدير** (توقع أقل من الحقيقي)، لو سالب يبقى **بالغ في التقدير**. الشكل المثالي هنا: توزيع متمركز حوالين الصفر (يعني مفيش انحياز منهجي لفوق أو لتحت) وضيق (يعني الأخطاء صغيرة).

**شرح الخلية:** حساب البواقي (residuals = القيمة الحقيقية - القيمة المتوقعة) لكل موديل، ورسم توزيعهم عشان نشوف هل الأخطاء متمركزة حوالين الصفر ولا لأ.
"""

residuals_cat_m1 = y_test_m1 - pred_cat_m1
residuals_lgbm_m1 = y_test_m1 - pred_lgbm_m1

plt.figure(figsize=(10, 5))
sns.histplot(residuals_cat_m1, color="#4C72B0", label="CatBoost", kde=True, stat="density", alpha=0.4, bins=60)
sns.histplot(residuals_lgbm_m1, color="#DD8452", label="LightGBM", kde=True, stat="density", alpha=0.4, bins=60)
plt.axvline(0, color="black", linestyle="--", linewidth=1)
plt.title("Model 1 — Residuals distribution (Actual − Predicted)")
plt.xlabel("Residual")
plt.legend()
plt.tight_layout()
plt.show()

"""### تصور بصري 4: Feature Importance

كل موديل بيديك ترتيب للفيتشرز حسب "قد إيه اعتمد عليها عشان ياخد قراره". ده أهم رسم في الموديل ده بالنسبة لينا كـ **sanity check نهائي** ضد الـ data leakage: المفروض `irradiance` (شدة الإشعاع الشمسي) تكون في القمة، لأنها فيزيائيًا أهم حاجة بتحدد الطاقة المنتجة من الألواح الشمسية. لو طلعلنا فيتشر غريب في القمة (زي `hour` لوحده مثلاً بشكل مبالغ فيه) هيبقى ده جرس إنذار إن فيه حاجة غلط.

**شرح الخلية:** استخراج ورسم أهمية الفيتشرز (Feature Importance) لكل من CatBoost وLightGBM في موديل 1، عشان نعرف الموديل اعتمد على أنهي فيتشرز أكتر في توقع active_power.
"""

cat_importance_m1 = pd.Series(
    cat_reg_m1.get_feature_importance(), index=X_train_m1.columns
).sort_values(ascending=False)

lgbm_importance_m1 = pd.Series(
    lgbm_reg_m1.feature_importances_, index=X_train_m1.columns
).sort_values(ascending=False)

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

cat_importance_m1.plot(kind="barh", ax=axes[0], color="#55A868")
axes[0].set_title("CatBoost — Feature Importance (Model 1)")
axes[0].invert_yaxis()

lgbm_importance_m1.plot(kind="barh", ax=axes[1], color="#C44E52")
axes[1].set_title("LightGBM — Feature Importance (Model 1)")
axes[1].invert_yaxis()

plt.tight_layout()
plt.show()

"""### خلاصة موديل 1

- الجدول فوق بيوضح مين الأدق بين CatBoost و LightGBM على الـ 3 مقاييس (MAE, RMSE, R²) — الموديل اللي MAE و RMSE بتاعته أقل، وR² بتاعته أقرب لـ 1، هو الأفضل هنا.
- شكل الـ **Predicted vs Actual**: لو النقط ملتصقة بالخط الأحمر في كل الأماكن (مش بس عند القيم الصغيرة) يبقى الموديل شاطر في كل الحالات، مش بس وقت الليل (لما `active_power` = 0 والتوقع سهل).
- شكل الـ **Residuals**: لو التوزيع متمركز عند الصفر ومفيش "ذيل" طويل، معناه الموديل مش بيغلط غلط ممنهج في اتجاه معين.
- **Feature Importance** هو التأكيد الأهم: لو `irradiance` (وربما `clear_sky_irradiance`, `sun_elevation`) هما الأعلى، يبقى الموديل فعلاً بيتعلم الفيزياء (كل ما الشمس أقوى كل ما الطاقة المنتجة أعلى) مش بيحفظ حاجة.

جاهز نكمل على **موديل 2 (`is_faulted` — Binary Classification)** بنفس الأسلوب؟

## MOdel 2

**شرح الخلية:** طباعة ملخص عام عن موديل 2: عدد عينات التدريب والاختبار، عدد الفيتشرز، وتوزيع الـ target (is_faulted) في مجموعة التدريب.
"""

print("=" * 70)
print("MODEL 2 : Fault Detection")
print("=" * 70)

print()

print("Training samples :", X_train_m2.shape[0])
print("Testing samples  :", X_test_m2.shape[0])

print()

print("Number of Features :", X_train_m2.shape[1])

print()

print("Target Distribution (Train)")
print(y_train_m2.value_counts())

print()

print("Target Distribution (%)")
print(round(y_train_m2.value_counts(normalize=True) * 100,2))

"""**شرح الخلية:** بناء جدول بسيط يعرض أسماء كل الفيتشرز المستخدمة في موديل 2."""

features_df = pd.DataFrame({

    "Feature":X_train_m2.columns

})

features_df

"""**شرح الخلية:** حساب أوزان الفئات (class weights) بطريقة balanced عشان نعالج مشكلة عدم توازن الفئات في is_faulted، ثم طباعتها."""

from sklearn.utils.class_weight import compute_class_weight

classes_m2 = np.unique(y_train_m2)

weights_m2 = compute_class_weight(

    class_weight="balanced",

    classes=classes_m2,

    y=y_train_m2

)

class_weights_m2 = dict(zip(classes_m2, weights_m2))

print(class_weights_m2)

"""**شرح الخلية:** رسم بياني يوضح الأوزان المحسوبة لكل فئة (Healthy / Fault) في موديل 2."""

plt.figure(figsize=(6,4))

plt.bar(

    ["Healthy","Fault"],

    class_weights_m2.values(),

    color=["steelblue","tomato"]

)

plt.title("Class Weights")

plt.ylabel("Weight")

plt.show()

"""**شرح الخلية:** تعريف وتدريب موديل CatBoost Classifier على بيانات موديل 2، مع استخدام أوزان الفئات المحسوبة للتعامل مع عدم التوازن."""

cat_model_m2 = CatBoostClassifier(

    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function="Logloss",
    eval_metric="F1",
    class_weights=class_weights_m2,
    random_state=42,
    verbose=100

)

cat_model_m2.fit(

    X_train_m2,
    y_train_m2

)

"""**شرح الخلية:** تعريف وتدريب موديل LightGBM Classifier على نفس بيانات موديل 2، مع استخدام أوزان الفئات كمان."""

lgbm_model_m2 = LGBMClassifier(

    n_estimators=500,
    learning_rate=0.05,
    max_depth=8,
    class_weight=class_weights_m2,
    random_state=42

)

lgbm_model_m2.fit(

    X_train_m2,
    y_train_m2

)

"""**شرح الخلية:** عمل تنبؤات على بيانات الاختبار باستخدام كل من موديل CatBoost وموديل LightGBM لموديل 2."""

pred_cat_m2 = cat_model_m2.predict(X_test_m2)

pred_lgbm_m2 = lgbm_model_m2.predict(X_test_m2)

"""**شرح الخلية:** استيراد مقاييس التقييم الخاصة بمشاكل التصنيف (accuracy, f1, classification_report, confusion_matrix)."""

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

"""**شرح الخلية:** طباعة تقرير تصنيف (classification report) مفصّل لكل من CatBoost وLightGBM في موديل 2، يوضح الـ precision والـ recall والـ f1-score لكل فئة."""

print("=" * 80)
print("CatBoost Classification Report")
print("=" * 80)

print(classification_report(
    y_test_m2,
    pred_cat_m2,
    target_names=["Healthy", "Fault"],
    digits=4
))

print("\n")

print("=" * 80)
print("LightGBM Classification Report")
print("=" * 80)

print(classification_report(
    y_test_m2,
    pred_lgbm_m2,
    target_names=["Healthy", "Fault"],
    digits=4
))

"""**شرح الخلية:** حساب مصفوفة الالتباس (confusion matrix) لكل من CatBoost وLightGBM في موديل 2."""

cm_cat = confusion_matrix(
    y_test_m2,
    pred_cat_m2
)

cm_lgb = confusion_matrix(
    y_test_m2,
    pred_lgbm_m2
)

"""**شرح الخلية:** رسم مصفوفتي الالتباس (Confusion Matrices) الخاصتين بـ CatBoost وLightGBM كخريطة حرارية بجانب بعض للمقارنة البصرية."""

fig,axes = plt.subplots(
    1,
    2,
    figsize=(13,5)
)

sns.heatmap(
    cm_cat,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Healthy","Fault"],
    yticklabels=["Healthy","Fault"],
    ax=axes[0]
)

axes[0].set_title("CatBoost")

axes[0].set_xlabel("Predicted")

axes[0].set_ylabel("Actual")

sns.heatmap(
    cm_lgb,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=["Healthy","Fault"],
    yticklabels=["Healthy","Fault"],
    ax=axes[1]
)

axes[1].set_title("LightGBM")

axes[1].set_xlabel("Predicted")

axes[1].set_ylabel("Actual")

plt.tight_layout()

plt.show()

"""**شرح الخلية:** بناء جدول بأهمية كل فيتشر حسب موديل CatBoost في موديل 2، مرتّب تنازليًا، وعرض أعلى 10 فيتشرز."""

importance_cat = pd.DataFrame({

    "Feature":X_train_m2.columns,

    "Importance":cat_model_m2.get_feature_importance()

})

importance_cat = importance_cat.sort_values(
    by="Importance",
    ascending=False
)

importance_cat.head(10)

"""**شرح الخلية:** رسم بياني عمودي لأعلى 10 فيتشرز أهمية حسب CatBoost في موديل 2."""

plt.figure(figsize=(10,6))

sns.barplot(

    data=importance_cat.head(10),

    x="Importance",

    y="Feature"

)

plt.title("Top 10 Important Features - CatBoost")

plt.show()

"""**شرح الخلية:** بناء جدول بأهمية كل فيتشر حسب موديل LightGBM في موديل 2، مرتّب تنازليًا، وعرض أعلى 10 فيتشرز."""

importance_lgb = pd.DataFrame({

    "Feature":X_train_m2.columns,

    "Importance":lgbm_model_m2.feature_importances_

})

importance_lgb = importance_lgb.sort_values(
    by="Importance",
    ascending=False
)

importance_lgb.head(10)

"""**شرح الخلية:** رسم بياني عمودي لأعلى 10 فيتشرز أهمية حسب LightGBM في موديل 2."""

plt.figure(figsize=(10,6))

sns.barplot(

    data=importance_lgb.head(10),

    x="Importance",

    y="Feature"

)

plt.title("Top 10 Important Features - LightGBM")

plt.show()

"""## MOdel 3

**شرح الخلية:** إعادة بناء فيتشرز وبيانات موديل 3 (توقع fault_labels) من جديد قبل التدريب مباشرة، مع استبعاد الفئة النادرة والمركّبة dc_string_outage|downtime من الـ train والـ test كمان هنا، ثم طباعة ملخص عن عدد العينات والفيتشرز وتوزيع الـ target.
"""

model3_drop_cols = leakage_cols_general
model3_features = [c for c in df.columns if c not in model3_drop_cols]

X_train_m3 = train_df[model3_features]
y_train_m3 = train_df["fault_labels"]
X_test_m3 = test_df[model3_features]
y_test_m3 = test_df["fault_labels"]

excluded_label_m3 = "dc_string_outage|downtime"
train_mask_m3 = y_train_m3 != excluded_label_m3
test_mask_m3 = y_test_m3 != excluded_label_m3

X_train_m3 = X_train_m3[train_mask_m3]
y_train_m3 = y_train_m3[train_mask_m3]
X_test_m3 = X_test_m3[test_mask_m3]
y_test_m3 = y_test_m3[test_mask_m3]

print("Training samples :", X_train_m3.shape[0])
print("Testing samples  :", X_test_m3.shape[0])
print("Number of Features :", X_train_m3.shape[1])
print("\nTarget Distribution in Train Set:")
print(y_train_m3.value_counts())
print("\nTarget Distribution (%) in Train Set:")
print(round(y_train_m3.value_counts(normalize=True) * 100, 3))

"""**شرح الخلية:** حساب أوزان الفئات (class weights) بطريقة balanced لمعالجة عدم توازن أنواع الأعطال في موديل 3، وطباعتها، ورسمها بيانيًا."""

classes_m3 = np.unique(y_train_m3)
weights_m3 = compute_class_weight(
    class_weight="balanced",
    classes=classes_m3,
    y=y_train_m3
)
class_weights_m3 = dict(zip(classes_m3, weights_m3))

print("\nComputed Class Weights:")
for cls, w in class_weights_m3.items():
    print(f"{cls:25s}: {w:.4f}")

plt.figure(figsize=(10, 4))
plt.bar(class_weights_m3.keys(), class_weights_m3.values(), color="teal")
plt.title("Calculated Class Weights for Multi-class Imbalance (Model 3)")
plt.ylabel("Weight")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""**شرح الخلية:** تعريف وتدريب موديل CatBoost Classifier (متعدد الفئات) على بيانات موديل 3 لتوقع نوع العطل، مع استخدام أوزان الفئات المحسوبة."""

cat_model_m3 = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function="MultiClass",
    eval_metric="TotalF1",
    class_weights=class_weights_m3,
    random_state=42,
    verbose=100
)

print("\nTraining CatBoost Model 3...")
cat_model_m3.fit(X_train_m3, y_train_m3)

"""**شرح الخلية:** تعريف وتدريب موديل LightGBM Classifier (متعدد الفئات) على نفس بيانات موديل 3."""

lgbm_model_m3 = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=8,
    objective="multiclass",
    class_weight=class_weights_m3,
    random_state=42
)

print("\nTraining LightGBM Model 3...")
lgbm_model_m3.fit(X_train_m3, y_train_m3)

"""**شرح الخلية:** عمل تنبؤات على بيانات الاختبار باستخدام كل من CatBoost وLightGBM لموديل 3."""

pred_cat_m3 = cat_model_m3.predict(X_test_m3).ravel()
pred_lgb_m3 = lgbm_model_m3.predict(X_test_m3)

"""**شرح الخلية:** طباعة تقرير تصنيف مفصّل لكل من CatBoost وLightGBM في موديل 3."""

print("=" * 80)
print("CatBoost Model 3 - Classification Report")
print("=" * 80)
print(classification_report(y_test_m3, pred_cat_m3, digits=4))

print("=" * 80)
print("LightGBM Model 3 - Classification Report")
print("=" * 80)
print(classification_report(y_test_m3, pred_lgb_m3, digits=4))

"""**شرح الخلية:** حساب ورسم مصفوفتي الالتباس الخاصتين بـ CatBoost وLightGBM لموديل 3 كخريطة حرارية للمقارنة بين أنواع الأعطال المتوقعة والحقيقية."""

cm_cat_m3 = confusion_matrix(y_test_m3, pred_cat_m3, labels=classes_m3)
cm_lgb_m3 = confusion_matrix(y_test_m3, pred_lgb_m3, labels=classes_m3)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.heatmap(
    cm_cat_m3, annot=True, fmt="d", cmap="Blues",
    xticklabels=classes_m3, yticklabels=classes_m3, ax=axes[0]
)
axes[0].set_title("CatBoost - Fault Labels Confusion Matrix")
axes[0].set_xlabel("Predicted Label")
axes[0].set_ylabel("Actual Label")
axes[0].tick_params(axis='x', rotation=45)

sns.heatmap(
    cm_lgb_m3, annot=True, fmt="d", cmap="Greens",
    xticklabels=classes_m3, yticklabels=classes_m3, ax=axes[1]
)
axes[1].set_title("LightGBM - Fault Labels Confusion Matrix")
axes[1].set_xlabel("Predicted Label")
axes[1].set_ylabel("Actual Label")
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""**شرح الخلية:** بناء جدولين بأهمية الفيتشرز حسب CatBoost وLightGBM في موديل 3، ورسم أعلى 10 فيتشرز لكل منهم جنب بعض."""

importance_cat_m3 = pd.DataFrame({
    "Feature": X_train_m3.columns,
    "Importance": cat_model_m3.get_feature_importance()
}).sort_values(by="Importance", ascending=False)

importance_lgb_m3 = pd.DataFrame({
    "Feature": X_train_m3.columns,
    "Importance": lgbm_model_m3.feature_importances_
}).sort_values(by="Importance", ascending=False)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.barplot(data=importance_cat_m3.head(10), x="Importance", y="Feature", ax=axes[0], color="steelblue")
axes[0].set_title("Top 10 Important Features - CatBoost (Model 3)")

sns.barplot(data=importance_lgb_m3.head(10), x="Importance", y="Feature", ax=axes[1], color="seagreen")
axes[1].set_title("Top 10 Important Features - LightGBM (Model 3)")

plt.tight_layout()
plt.show()

"""## Model 4

**شرح الخلية:** طباعة ملخص عام عن موديل 4: عدد عينات التدريب والاختبار، عدد الفيتشرز، وتوزيع الـ target (fault_severity) في مجموعة التدريب.
"""

print("=" * 70)
print("MODEL 4 : Fault Severity Detection")
print("=" * 70)
print()
print("Training samples :", X_train_m4.shape[0])
print("Testing samples :", X_test_m4.shape[0])
print("Number of Features :", X_train_m4.shape[1])
print("\nTarget Distribution in Train Set:")
print(y_train_m4.value_counts())
print("\nTarget Distribution (%) in Train Set:")
print(round(y_train_m4.value_counts(normalize=True) * 100, 3))

"""**شرح الخلية:** حساب أوزان الفئات (class weights) بطريقة balanced لمعالجة عدم توازن مستويات شدة العطل في موديل 4، وطباعتها ورسمها بيانيًا."""

classes_m4 = np.unique(y_train_m4)
weights_m4 = compute_class_weight(
    class_weight="balanced",
    classes=classes_m4,
    y=y_train_m4
)
class_weights_m4 = dict(zip(classes_m4, weights_m4))

print("\nComputed Class Weights for Model 4:")
for cls, w in class_weights_m4.items():
    print(f"Class {cls}: {w:.4f}")

plt.figure(figsize=(8, 4))
plt.bar([str(c) for c in class_weights_m4.keys()], class_weights_m4.values(), color="purple")
plt.title("Calculated Class Weights for Multi-class Imbalance (Model 4)")
plt.xlabel("Fault Severity Class (0: None, 1: Low, 2: Medium, 3: High)")
plt.ylabel("Weight")
plt.tight_layout()
plt.show()

"""**شرح الخلية:** تعريف وتدريب موديل CatBoost Classifier (متعدد الفئات) على بيانات موديل 4 لتوقع شدة العطل."""

cat_model_m4 = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function="MultiClass",
    eval_metric="TotalF1",
    class_weights=class_weights_m4,
    random_state=42,
    verbose=100
)

print("\nTraining CatBoost Model 4...")
cat_model_m4.fit(X_train_m4, y_train_m4)

"""**شرح الخلية:** تعريف وتدريب موديل LightGBM Classifier (متعدد الفئات) على نفس بيانات موديل 4."""

lgbm_model_m4 = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=8,
    objective="multiclass",
    class_weight=class_weights_m4,
    random_state=42
)

print("\nTraining LightGBM Model 4...")
lgbm_model_m4.fit(X_train_m4, y_train_m4)

"""**شرح الخلية:** عمل تنبؤات على بيانات الاختبار وطباعة تقرير تصنيف مفصّل لكل من CatBoost وLightGBM في موديل 4."""

pred_cat_m4 = cat_model_m4.predict(X_test_m4).ravel()
pred_lgb_m4 = lgbm_model_m4.predict(X_test_m4)

print("\n" + "=" * 80)
print("CatBoost Model 4 - Classification Report")
print("=" * 80)
print(classification_report(y_test_m4, pred_cat_m4, digits=4))

print("=" * 80)
print("LightGBM Model 4 - Classification Report")
print("=" * 80)
print(classification_report(y_test_m4, pred_lgb_m4, digits=4))

"""**شرح الخلية:** حساب ورسم مصفوفتي الالتباس الخاصتين بـ CatBoost وLightGBM لموديل 4 كخريطة حرارية."""

cm_cat_m4 = confusion_matrix(y_test_m4, pred_cat_m4, labels=classes_m4)
cm_lgb_m4 = confusion_matrix(y_test_m4, pred_lgb_m4, labels=classes_m4)

severity_labels = ["None (0)", "Low (1)", "Medium (2)", "High (3)"]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.heatmap(
    cm_cat_m4, annot=True, fmt="d", cmap="Blues",
    xticklabels=severity_labels, yticklabels=severity_labels, ax=axes[0]
)
axes[0].set_title("CatBoost - Fault Severity Confusion Matrix")
axes[0].set_xlabel("Predicted Severity")
axes[0].set_ylabel("Actual Severity")

sns.heatmap(
    cm_lgb_m4, annot=True, fmt="d", cmap="Greens",
    xticklabels=severity_labels, yticklabels=severity_labels, ax=axes[1]
)
axes[1].set_title("LightGBM - Fault Severity Confusion Matrix")
axes[1].set_xlabel("Predicted Severity")
axes[1].set_ylabel("Actual Severity")

plt.tight_layout()
plt.show()

"""**شرح الخلية:** بناء جدولين بأهمية الفيتشرز حسب CatBoost وLightGBM في موديل 4، ورسم أعلى 10 فيتشرز لكل منهم جنب بعض."""

importance_cat_m4 = pd.DataFrame({
    "Feature": X_train_m4.columns,
    "Importance": cat_model_m4.get_feature_importance()
}).sort_values(by="Importance", ascending=False)

importance_lgb_m4 = pd.DataFrame({
    "Feature": X_train_m4.columns,
    "Importance": lgbm_model_m4.feature_importances_
}).sort_values(by="Importance", ascending=False)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.barplot(data=importance_cat_m4.head(10), x="Importance", y="Feature", ax=axes[0], color="steelblue")
axes[0].set_title("Top 10 Important Features - CatBoost (Model 4)")

sns.barplot(data=importance_lgb_m4.head(10), x="Importance", y="Feature", ax=axes[1], color="mediumseagreen")
axes[1].set_title("Top 10 Important Features - LightGBM (Model 4)")

plt.tight_layout()
plt.show()

"""## Evaluate all Models

**شرح الخلية:** تجميع نتائج موديلات التصنيف الثلاثة فقط (موديل 2، 3، 4) — Accuracy وF1-Score بنوعيه Macro وWeighted — لكل من CatBoost وLightGBM في جدول واحد ورسمه بيانيًا. موديل 1 اتشال من اللوب ده لأنه Regression (بيتوقع رقم مستمر active_power مش فئة)، فمقاييس زي accuracy_score مش منطقية له أصلاً — ده كان باج موجود في النوتبوك الأصلي بيسبب ValueError. نتايج موديل 1 (MAE/RMSE/R2) بتتعرض هنا لوحدها من results_m1_df اللي اتحسبت قبل كده.
"""

models_info = [
    ("Model 2: Fault Cause", y_test_m2, pred_cat_m2, pred_lgbm_m2),
    ("Model 3: Component at Fault", y_test_m3, pred_cat_m3, pred_lgb_m3),
    ("Model 4: Fault Severity", y_test_m4, pred_cat_m4, pred_lgb_m4)
]

evaluation_results = []

for model_name, y_true, pred_cat, pred_lgb in models_info:

    acc_cat = accuracy_score(y_true, pred_cat)
    f1_macro_cat = f1_score(y_true, pred_cat, average='macro')
    f1_weighted_cat = f1_score(y_true, pred_cat, average='weighted')

    evaluation_results.append({
        "Model Task": model_name,
        "Algorithm": "CatBoost",
        "Accuracy": acc_cat,
        "F1-Score (Macro)": f1_macro_cat,
        "F1-Score (Weighted)": f1_weighted_cat
    })

    acc_lgb = accuracy_score(y_true, pred_lgb)
    f1_macro_lgb = f1_score(y_true, pred_lgb, average='macro')
    f1_weighted_lgb = f1_score(y_true, pred_lgb, average='weighted')

    evaluation_results.append({
        "Model Task": model_name,
        "Algorithm": "LightGBM",
        "Accuracy": acc_lgb,
        "F1-Score (Macro)": f1_macro_lgb,
        "F1-Score (Weighted)": f1_weighted_lgb
    })

results_df = pd.DataFrame(evaluation_results)

print("=" * 85)
print("MODEL 1 (Regression - active_power) IS EVALUATED SEPARATELY WITH MAE / RMSE / R2")
print("=" * 85)
display(results_m1_df)

print("=" * 85)
print("COMPREHENSIVE MODELS EVALUATION SUMMARY (Classification Models: 2, 3, 4)")
print("=" * 85)
display(results_df.style.format({
    "Accuracy": "{:.4f}",
    "F1-Score (Macro)": "{:.4f}",
    "F1-Score (Weighted)": "{:.4f}"
}).background_gradient(cmap='viridis', subset=['F1-Score (Macro)', 'Accuracy']))

sns.set_theme(style="whitegrid")

fig, axes = plt.subplots(2, 1, figsize=(14, 12))

sns.barplot(
    data=results_df,
    x="Model Task",
    y="F1-Score (Macro)",
    hue="Algorithm",
    palette=["#1f77b4", "#2ca02c"],
    ax=axes[0]
)
axes[0].set_title("Comparison of F1-Score (Macro) Across Classification Models", fontsize=16, fontweight='bold')
axes[0].set_ylabel("F1-Score (Macro)", fontsize=12)
axes[0].set_xlabel("")
axes[0].set_ylim(0, 1.1)
axes[0].legend(title="Algorithm", loc='upper right')

for p in axes[0].patches:
    axes[0].annotate(format(p.get_height(), '.3f'),
                     (p.get_x() + p.get_width() / 2., p.get_height()),
                     ha = 'center', va = 'center',
                     xytext = (0, 9),
                     textcoords = 'offset points',
                     fontsize=10)

sns.barplot(
    data=results_df,
    x="Model Task",
    y="Accuracy",
    hue="Algorithm",
    palette=["#1f77b4", "#2ca02c"],
    ax=axes[1]
)
axes[1].set_title("Comparison of Accuracy Across Classification Models", fontsize=16, fontweight='bold')
axes[1].set_ylabel("Accuracy", fontsize=12)
axes[1].set_xlabel("Model Task", fontsize=12)
axes[1].set_ylim(0, 1.1)
axes[1].legend(title="Algorithm", loc='upper right')

for p in axes[1].patches:
    axes[1].annotate(format(p.get_height(), '.3f'),
                     (p.get_x() + p.get_width() / 2., p.get_height()),
                     ha = 'center', va = 'center',
                     xytext = (0, 9),
                     textcoords = 'offset points',
                     fontsize=10)

plt.tight_layout()
plt.show()